### ISSUE TITLE
Researching cultural center in Tauceti will causes bug when Aquarius sign is active

### ISSUE THREAD

**Issue by TBB000623** [pmotschmann/Evolve#1035]
All detailed income lists can't work correctly.

bug report in Console
```
main.js:1 Uncaught TypeError: Cannot create property 'ᄂAquarius' on number '0'
    at main.js:1:1749217
    at Worker.<anonymous> (main.js:1:1754877)
```

**Comment by fredden** [comment]
It looks like https://github.com/pmotschmann/Evolve/pull/1034 fixes this problem.
