### ISSUE TITLE
Tech pages in wiki do not load

### ISSUE THREAD

**Issue by calvinjhchan** [pmotschmann/Evolve#1268]
None of the tech pages are loading and UI is stuck showing search if navigating to it. Console error is:

`wiki.js:352 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at Object.title (wiki.js:352:47901)
    at wiki.js:422:78183
    at Array.forEach (<anonymous>)
    at Od (wiki.js:422:78048)
    at Cd (wiki.js:422:79548)
    at wiki.js:422:83576
    at Array.forEach (<anonymous>)
    at ot (wiki.js:422:83358)
    at wn (wiki.js:1616:2991)
    at Cr.loadPage (wiki.js:1616:2050)
title	@	wiki.js:352
(anonymous)	@	wiki.js:422
Od	@	wiki.js:422
Cd	@	wiki.js:422
(anonymous)	@	wiki.js:422
ot	@	wiki.js:422
wn	@	wiki.js:1616
loadPage	@	wiki.js:1616
click	@	VM3893:3
dn	@	vue.min.js:11
r	@	vue.min.js:11
dn	@	vue.min.js:11
r	@	vue.min.js:11
i._wrapper	@	vue.min.js:11`

Appears to be an issue with the line "e.resource.Elysanite.name"

**Comment by yarukishi** [comment]
Can you provide a save file that reproduces the issue?
