### ISSUE TITLE
TypeError in Wiki when rendering Symposium

### ISSUE THREAD

**Issue by Saucistophe** [pmotschmann/Evolve#1309]
When browsing the Wiki page for intergalactic structures, the pages crashes mid-rendering.

![image](https://github.com/user-attachments/assets/5ab1b9e0-2e62-4db2-a4e2-d43c9dc179fa)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'on')
    at Rt (wiki.js:170:165466)
    at Object.effect (wiki.js:170:143336)
    at p (wiki.js:413:116681)
    at wa (wiki.js:413:116694)
    at wiki.js:422:4340
    at Array.forEach (<anonymous>)
    at wiki.js:422:4050
    at Array.forEach (<anonymous>)
    at Md (wiki.js:422:3827)
    at jc (wiki.js:413:112164)
```

**Comment by Saucistophe** [comment]
[evolve-2024-12-09-14-52.txt](https://github.com/user-attachments/files/18062410/evolve-2024-12-09-14-52.txt)
My save, in case that helps reproducing.

**Comment by yarukishi** [comment]
This should be resolved in v1.4.3.
